---
# handlers file for server
- name: enable prometheus
  systemd:
    name: prometheus
    daemon_reload: true
    enabled: yes

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded