---
# defaults file for server
prometheus_version: "2.24.1"

prometheus_bin_dir: /usr/local/bin
prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_web_url: "http://localhost:9090"
