- name: Create configuration directory
  ansible.builtin.file:
    state: directory
    dest: "{{ prometheus_config_dir }}"
    owner: root
    group: root
    mode: "755"

- name: Create main configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: root
    group: root
    mode: "644"
  notify:
    - reload prometheus